export default {
    currentUser: {
        first_name: "Petya",
        second_name: "Pupkin",
        avatar: "/path/to/avatar.jpg",
        email: "my@email.com",
        login: "userLogin",
        phone: "8(911)-222-33-22",
    },
    _404: {
        label: "404",
        subLabel: "Возможно эту страницу кто-то уволок...",
        extendClass: "title--big",
        link: {
            label: "Вернуться в чат",
            href: "messenger",
        },
    },
    _500: {
        label: "500",
        subLabel: "Сохраняйте спокойстиве и возвращайтесь в свой чат",
        extendClass: "title--big",
        link: {
            label: "Вернуться в чат",
            href: "messenger",
        },
    },
    messenger: {
        link: {
            label: "Профиль",
            href: "profile",
        },
        chats: [
            {
                id: 123,
                title: "Новый чат",
                avatar: "",
                unread_count: 1,
                last_message: {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "s",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content:
                        "Это сообщение было последним2 Это сообщение было последним2 Это сообщение было последним2",
                },
            },
            {
                id: 1232,
                title: "Новый чат2",
                avatar: "",
                unread_count: null,
                last_message: {
                    user: {
                        first_name: "Petya1",
                        second_name: "Pupkin1",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin2321",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2021-01-02T14:22:22.000Z",
                    content: "Это сообщение было последним2",
                },
            },
        ],
        search: {
            element: {
                name: "search",
                type: "text",
                label: "Поиск",
                error: false,
                errorDescription: "",
                hint: false,
                placeholder: "🔎 Поиск",
                autocomplete: false,
                disabled: false,
            },
            input: "",
            result: "",
        },
        selectedChat: {
            title: "Новый чат",
            avatar: "",
            messages: [
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogi2n",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogi2n",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogi2n",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogi2n",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
                {
                    user: {
                        first_name: "Petya",
                        second_name: "Pupkin",
                        avatar: "/path/to/avatar.jpg",
                        email: "my@email.com",
                        login: "userLogin",
                        phone: "8(911)-222-33-22",
                    },
                    time: "2020-01-02T14:22:22.000Z",
                    content: "asdasdasdsa",
                },
            ],
        },
    },
    login: {
        label: "Авторизация",
        formName: "login",
        data: [
            {
                name: "login",
                type: "text",
                label: "Логин",
                hint: false,
                placeholder: "Введите логин",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "password",
                type: "password",
                label: "Пароль",
                hint: false,
                placeholder: "Введите пароль",
                autocomplete: false,
                disabled: false,
            },
        ],
        controls: [
            {
                name: "login",
                type: "submit",
                isButton: true,
                label: "Войти",
                disabled: false,
                form: "login",
            },
            {
                name: "registration",
                href: "registration",
                isButton: false,
                label: "Ещё не зарегистрированы?",
                extendClass: "",
            },
        ],
    },
    profile: {
        label: "Профиль",
        formName: "profile",
        link: {
            href: "messenger",
        },
        data: [
            {
                name: "email",
                type: "email",
                label: "Почта",
                hint: false,
                autocomplete: false,
                disabled: true,
                value: "yuelmanov@mail.com",
            },
            {
                name: "login",
                type: "text",
                label: "Логин",
                hint: false,
                autocomplete: false,
                disabled: true,
                value: "yuelmanov",
            },
            {
                name: "first_name",
                type: "text",
                label: "Имя",
                hint: false,
                autocomplete: false,
                disabled: true,
                value: "Юра",
            },
            {
                name: "second_name",
                type: "text",
                label: "Фамилия",
                hint: false,
                autocomplete: false,
                disabled: true,
                value: "Елманов",
            },
            {
                name: "display_name",
                type: "text",
                label: "Имя в чате",
                hint: false,
                autocomplete: false,
                disabled: true,
                value: null,
            },
            {
                name: "phone",
                type: "tel",
                label: "Телефон",
                hint: false,
                autocomplete: false,
                disabled: true,
                value: "+79999999999",
            },
        ],
        controls: [
            {
                name: "editProfile",
                href: "profile/edit/data",
                isButton: false,
                label: "Изменить данные",
                extendClass: "",
            },
            {
                name: "editPassword",
                href: "profile/edit/password",
                isButton: false,
                label: "Изменить пароль",
                extendClass: "",
            },
            {
                name: "exit",
                href: "login",
                isButton: false,
                label: "Выйти",
                extendClass: "red",
            },
        ],
    },
    profileEditData: {
        label: "Редактирование данных в профиле",
        formName: "editData",
        link: {
            href: "messenger",
        },
        data: [
            {
                name: "email",
                type: "email",
                label: "Почта",
                hint: false,
                autocomplete: false,
                disabled: false,
                value: "yuelmanov@mail.com",
            },
            {
                name: "login",
                type: "text",
                label: "Логин",
                hint: false,
                autocomplete: false,
                disabled: false,
                value: "yuelmanov",
            },
            {
                name: "first_name",
                type: "text",
                label: "Имя",
                hint: false,
                autocomplete: false,
                disabled: false,
                value: "Юра",
            },
            {
                name: "second_name",
                type: "text",
                label: "Фамилия",
                hint: false,
                autocomplete: false,
                disabled: false,
                value: "Елманов",
            },
            {
                name: "display_name",
                type: "text",
                label: "Имя в чате",
                hint: false,
                autocomplete: false,
                disabled: false,
                value: null,
            },
            {
                name: "phone",
                type: "tel",
                label: "Телефон",
                hint: false,
                autocomplete: false,
                disabled: false,
                value: "+79999999999",
            },
        ],
        controls: [
            {
                name: "save",
                type: "submit",
                isButton: true,
                label: "Сохранить",
                form: "editData",
            },
            {
                name: "profile",
                href: "profile",
                isButton: false,
                label: "Назад в профиль",
                extendClass: "",
            },
        ],
    },
    profileEditPassword: {
        label: "Изменить пароль",
        formName: "editPassword",
        link: {
            href: "messenger",
        },
        data: [
            {
                name: "oldPassword",
                type: "password",
                label: "Старый пароль",
                hint: false,
                autocomplete: false,
                disabled: false,
            },
            {
                name: "newPassword",
                type: "password",
                label: "Новый пароль",
                hint: false,
                autocomplete: false,
                disabled: false,
            },
            {
                name: "newPasswordConfirm",
                type: "password",
                label: "Новый пароль (еще раз)",
                hint: false,
                autocomplete: false,
                disabled: false,
            },
        ],
        controls: [
            {
                name: "save",
                type: "submit",
                isButton: true,
                label: "Сохранить",
                form: "editPassword",
            },
            {
                name: "profile",
                href: "profile",
                isButton: false,
                label: "Назад в профиль",
                extendClass: "",
            },
        ],
    },
    registration: {
        label: "Регистрация",
        formName: "registration",
        data: [
            {
                name: "email",
                type: "email",
                label: "Почта",
                hint: false,
                placeholder: "Введите почту example@mail.com",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "login",
                type: "text",
                label: "Логин",
                hint: false,
                placeholder: "Введите логин",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "first_name",
                type: "text",
                label: "Имя",
                hint: false,
                placeholder: "Введите имя",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "second_name",
                type: "text",
                label: "Фамилия",
                hint: false,
                placeholder: "Введите фамилию",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "phone",
                type: "tel",
                label: "Телефон",
                hint: false,
                placeholder: "Введите телефон +7 999 999 99 99",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "password",
                type: "password",
                label: "Пароль",
                hint: true,
                hintDescription: "Пароль должен быть не менее 8 символов",
                placeholder: "Введите пароль",
                autocomplete: false,
                disabled: false,
            },
            {
                name: "passwordConfirm",
                type: "password",
                label: "Пароль (еще раз)",
                hint: false,
                placeholder: "Повторите введеный пароль выше",
                autocomplete: false,
                disabled: false,
            },
        ],
        controls: [
            {
                name: "send",
                type: "submit",
                isButton: true,
                label: "Создать аккаунт",
                disabled: false,
                form: "registration",
            },
            {
                name: "login",
                href: "login",
                isButton: false,
                label: "Войти",
                extendClass: "",
            },
        ],
    },
};
